[package]
name = "frozenight-ffi"
version = "1.0.0"
edition = "2021"

[lib]
name = "frozenight_ffi"
crate-type = ["cdylib", "staticlib"]

[dependencies]
frozenight = { git = "https://github.com/CrispStrobe/frozenight", branch = "main" }
cozy-chess = "0.3"
bytemuck = { version = "1", features = ["derive"] }

[profile.release]
lto = true
panic = "abort"
opt-level = 3

