name: crispchess
description: Cross-platform chess app with pluggable engines.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  chess: ^0.8.1
  flutter_svg: ^2.2.3
  logging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pieces/
