#!/usr/bin/env python3
"""Generate the position list the Lc0 oracle runs on.

Every case is a *move sequence from the initial position*, not a bare FEN, so
that our engine and lc0 see the same history planes. Feeding a bare FEN would
leave lc0 to invent history with --history-fill and make any difference
unattributable.

Four cases are hand-built to make a specific plane observable; the rest are
random legal games at assorted lengths, which is where the bugs nobody
predicted show up. Deterministic: same seed, same file, so a re-run of the
oracle compares like with like.

    python3 tool/oracle/gen_positions.py > tool/oracle/positions.txt
"""
import random
import sys

import chess


def targeted():
    """Cases aimed at a specific input plane."""
    yield "startpos", []

    # Castling planes 104-107. White gives up the h-rook right (Rh1-g1) and
    # Black the a-rook right (Ra8-b8), so the four rights are KQkq -> Q...k:
    # asymmetric both within and between colours. With all four rights set —
    # as in the opening — a kingside/queenside mix-up is invisible, so a test
    # that only ever looks at the start position cannot see this.
    yield "asymmetric-castling", "g1f3 b8c6 h1g1 a8b8".split()

    # Plane 109 is the rule-50 counter. Only a long stretch without a capture
    # or a pawn move makes its scale visible.
    yield "high-rule50", ("g1f3 g8f6 b1c3 b8c6 f3g5 c6b4 c3b5 f6g4 "
                          "g5h3 g4h6 b5c3 b4c6 h3g5 h6g8 c3b5 c6b4").split()

    # Repetition plane (plane 12 of each history slot).
    yield "repetition", "g1f3 g8f6 f3g1 f6g8 g1f3 g8f6 f3g1 f6g8".split()


def random_games(count, rng):
    """Random legal games, truncated at a random ply."""
    for i in range(count):
        board = chess.Board()
        target = rng.choice([2, 4, 6, 9, 12, 16, 20, 26, 32, 40, 52, 64])
        moves = []
        while len(moves) < target and not board.is_game_over(claim_draw=False):
            move = rng.choice(list(board.legal_moves))
            moves.append(move.uci())
            board.push(move)
        if moves:
            yield f"random-{i:02d}-ply{len(moves)}", moves


def main():
    rng = random.Random(20260904)
    print("# name<TAB>uci moves from the initial position")
    print("# generated by tool/oracle/gen_positions.py — do not hand-edit")
    for name, moves in targeted():
        print(f"{name}\t{' '.join(moves)}")
    for name, moves in random_games(36, rng):
        print(f"{name}\t{' '.join(moves)}")


if __name__ == "__main__":
    main()
