"""Write a benchmark of board images with known FENs, for any recognizer.

    python3 tool/board_vision/bench.py --out /tmp/bv_bench

For every piece style (the SVG sets and the permissive glyph fonts) it
renders boards of plausible positions — one king each, pawns never on the
back ranks, White's king in the lower half — half as screen captures and half
as print diagrams, through the same capture damage as the training data (low
resolution, slight rotation and perspective, paper, light, blur, JPEG). Writes <style>_<n>.png and
labels.tsv: file, FEN placement, style, look (screen|book), and the board's
pixel rect (left, top, size = width, height) for recognizers that take a
crop.

The images depict the piece sets, so they carry the sets' licences; see the
README "Training data licences" (three sets are CC BY 4.0 and need credit).
"""

import argparse
import os
import random
import sys

sys.path.insert(0, os.path.dirname(__file__))
import render as R  # noqa: E402

# One entry per piece design: DejaVu Sans Bold shares DejaVu Sans's shapes.
STYLES = R.SVG_SETS + [f for f in R.FONT_SETS if f != 'font-dejavu-bold']


def plausible_position(rng):
    board = [['.'] * 8 for _ in range(8)]
    free = [(r, c) for r in range(8) for c in range(8)]
    rng.shuffle(free)

    def put(code, rows):
        for i, (r, c) in enumerate(free):
            if r in rows:
                board[r][c] = code
                free.pop(i)
                return

    put('K', range(4, 8))
    put('k', range(0, 4))
    for _ in range(rng.randint(2, 8)):
        put('P', range(2, 7))
    for _ in range(rng.randint(2, 8)):
        put('p', range(1, 6))
    for code in 'NBRQnbrq':
        for _ in range(rng.choice([0, 1, 1, 2])):
            put(code, range(8))
    return board


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--out', required=True)
    ap.add_argument('--per-style', type=int, default=12)
    ap.add_argument('--seed', type=int, default=2026)
    ap.add_argument('--plain', action='store_true',
                    help='no capture damage beyond blur/noise/JPEG (the '
                         'first benchmark\'s recipe)')
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    rng = random.Random(a.seed)
    rows = ['file\tplacement\tstyle\tlook\tleft\ttop\tsize\theight']
    for style in STYLES:
        for n in range(a.per_style):
            board = plausible_position(rng)
            if a.plain:
                # The first benchmark's look: two screen boards to one book
                # board, no capture geometry or low resolution.
                look = 'book' if n % 3 == 2 else 'screen'
                img, (ox, oy, cell) = R.render_board(
                    board, style, rng, style=look, margin=rng.randint(0, 30))
                img = R.degrade(img, rng)
                ch = cell
            else:
                look = 'book' if n % 2 == 1 else 'screen'
                lowres = rng.random() < 0.3
                cell = rng.randint(12, 26) if lowres else rng.randint(22, 90)
                img, rect = R.render_board(board, style, rng, cell=cell,
                                           style=look,
                                           margin=rng.randint(0, 30))
                img, (ox, oy, cw, ch) = R.capture(img, rect, rng, look,
                                                  lowres=lowres)
                cell = cw
            name = f'{style}_{n:02d}.png'
            img.save(os.path.join(a.out, name), optimize=True)
            rows.append(f'{name}\t{R.placement_to_fen(board)}\t{style}\t{look}'
                        f'\t{ox:.2f}\t{oy:.2f}\t{8 * cell:.2f}\t{8 * ch:.2f}')
    with open(os.path.join(a.out, 'labels.tsv'), 'w') as f:
        f.write('\n'.join(rows) + '\n')
    with open(os.path.join(a.out, 'README.txt'), 'w') as f:
        f.write(__doc__.strip() + '\n\nGenerated by tool/board_vision/bench.py '
                f'--seed {a.seed} --per-style {a.per_style}'
                f'{" --plain" if a.plain else ""}.\n')
    print('wrote', len(rows) - 1, 'boards to', a.out)


if __name__ == '__main__':
    main()
